### ISSUE TITLE
Map and graphics revision

### ISSUE THREAD

**Issue by Davidek523** [PyCeas/Pyceas#57]
# Overview

Explain the problem, feature, or improvement you are addressing. For example:
> We need to optimize the integration of Tiled maps to improve performance and flexibility using JSON.

I noticed that the current map is not very easy to work with when it comes to the layers in the TMX file. Every layer addresses every part of the map in tiles instead of objects, which makes it more difficult to get the object and draw it in the game. I want to create more object layers and add the appropriate objects to those layers for easier extraction in code.

There has also been a mention of animations on the map. I noticed that in the tilesets we use, there are plenty of multiple tiles that together form an animation. There are even some GIFs showcasing those animations. I want to extract those tiles from the tileset, organize them into their own folders, and implement those animations into the map. This way, the game's map will feel more alive and less static.

Another thing I noticed in the layers of the tiled map is that the players (ships) are represented as a bunch of tiles put together. This is not very efficient when trying to get the image of the player in the code. I will extract the player ships from the tileset along with their animations and organize them into a folder, making it easier for the developers to draw the player onto the screen and animate it as well.

---

## User Stories

<details>
<summary>User Story 1: [Map and grahpics revision, "More clarified layers that are easier to use"]</summary>

### **Description**
- [x] #58

### **Tasks**
- [ ] Task 1: Judge which layers are be objects saved as a bunch of tiles 
- [ ] Task 2: Replace those layers with a object layer.
- [ ] Task 3: Convert* the images that are tiles into a actual image
- [ ] Task 4: Make a folder for these converted* images
- [ ] Task 5: Make a new tileset in Tiled and add the converted* images to the tileset
- [ ] Task 6: Add those images to the object layers and save it.

converted* = images that are a bunch of tiles, are put toghether in a graphical program and exported as one solid image.

### **Guidance for Contributors**

- Reference the file: N/A
- Relevant modules: N/A.
- Check related issues: N/A.
- Suggested resources: [Documentation Link](https://github.com/ultimateownsz/PySeas/tree/main/docs).
- Feel free to comment here or reach out on Discord for help.

</details>

<details>
<summary>User Story 2: [Animated map and objects, "A way for the developers to animate the images"]</summary>

### **Description**
- [x] #59

### **Tasks**
- [ ] Task 1: Extract tiles from the tileset that are responsible for animation
- [ ] Task 2: Organize the tiles by making sepcific folders for those tiles
- [ ] Task 3: Add a script for a easier way to extract the images from the folders.
- [ ] Task 4: In Tiled add a object layer/layers to determine where on the map we want to animate it
- [ ] Task 5: Add a new for loop that will get the position from the object layer that will be animated
- [ ] Task 6: Create a new class where the animation logic will be applied

### **Guidance for Contributors**

- Reference the file: N/A.
- Relevant modules: N/A.
- Check related issues: N/A
- Suggested resources: [Documentation Link](https://github.com/ultimateownsz/PySeas/tree/main/docs
- Feel free to comment here or reach out on Discord for help.

</details>

---

# Notes for Maintainers

- When reviewing this issue, user stories can be converted into individual issues if needed.
- Ensure guidance for each user story is clear and actionable.
- Update the original issue with links to the newly created user story issues for tracking.

---

# Additional Information

- Related files or code paths: `/src/maps`, `/src/dynamic_objects`.
- Documentation: [JSON Configuration Guide](https://example.com).
- Discord: [Join the discussion](https://discord.gg/s2P9fZbeZs).

**Comment by ultimateownsz** [comment]
I approve these issues! I converted your user stories to issues. Wasn't sure it the tasks would come with it, they don't unfortunately do you have to manually copy and paste them inti the new issues!
